services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Asia/Seoul
      - DATABASE_URL=postgresql://user:password@db/newsdb
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      # Nginx 컨테이너의 80 포트를 호스트의 3000 포트와 연결
      - "3000:80"
    depends_on:
      - backend
    environment:
      - TZ=Asia/Seoul

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d newsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsdb
    ports:
      - "5432:5432"

volumes:
  postgres_data:
