name: CI/CD for News Service
on:
  push:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/news-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/news-frontend:latest
          # build-args는 그대로 유지하여 프론트엔드 빌드에 Secret 값을 전달합니다.
          build-args: |
            REACT_APP_API_BASE_URL=${{ secrets.PROD_REACT_APP_API_BASE_URL }}

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 프로젝트 폴더로 이동
            cd /home/minjeong/ai-news
            
            # Docker Hub에서 최신 이미지들을 내려받음
            docker compose pull
            
            # 최신 이미지로 컨테이너를 다시 시작함
            docker compose up -d --force-recreate
            
            # 사용하지 않는 이전 Docker 이미지들을 정리하여 용량 확보
            docker image prune -f